# Generated by Django 3.2 on 2022-02-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Payment_method',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Shipping_charge',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='products',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Shipping_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
