# Generated by Django 3.2 on 2022-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_auto_20220227_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='product_name',
            new_name='Payment_method',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='price',
            new_name='Shipping_charge',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='quantity',
            new_name='sub_total',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Shipping_charge',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Payment_method',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_total',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
