# Generated by Django 3.2.4 on 2021-06-26 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recipient', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('GSTno', models.CharField(max_length=15)),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemno', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.TextField(max_length=200)),
                ('hsncode', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billmanage.bill')),
            ],
        ),
    ]
