# Generated by Django 3.2.4 on 2021-06-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bill',
            new_name='billno',
        ),
        migrations.AlterField(
            model_name='bill',
            name='billno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
