# Generated by Django 3.2 on 2022-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0003_alter_item_hsncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sgst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
