# Generated by Django 3.2 on 2022-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0004_alter_bill_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
