# Generated by Django 3.2 on 2022-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0005_auto_20220315_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cgst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
