# Generated by Django 3.2 on 2022-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0006_alter_bill_cgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='issuby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
